services:
  - type: web
    name: ocr-web-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: gcv-key.json
    secretFiles:
      - name: gcv-key.json
        mountPath: gcv-key.json
    plan: free